import { createSlice } from '@reduxjs/toolkit';
import imageOne from '../../../images/bmw_m6_dark_knight.jpg';
import imageTwo from '../../../images/bmw-m4-dtm-champion-edition-3840x2160-hd-3238.jpg';
import imageThree from '../../../images/bmw-m8-gte-2560x1440-artwork-hd-11479.jpg';
import imageFour from '../../../images/challenger.jpg';
import imageFive from '../../../images/challenger1.jpeg';
import imageSix from '../../../images/challenger2.jpg';
import imageSeven from '../../../images/dodge-challenger-srt-demon-2880x1800-2018-hd-7236.jpg';
import imageEight from '../../../images/ferrari-f8-tributo-5120x2880-geneva-motor-show-2019-4k-17515.jpg';
import imageNine from '../../../images/ford_mustang_muscle_car-wide.jpg';
import imageTen from '../../../images/image_20171103172326.jpg';
import imageEleven from '../../../images/lamborghini-aventador-s-roadster-3840x2160-2019-4k-18432.jpeg';
import imageTwelve from '../../../images/mansory_g63_star_trooper_pickup_09.jpg';
import imageThirteen from '../../../images/mansory_mercedes-benz_g-class_6x6_09.jpg';
import imageFourteen from '../../../images/mclaren-570s-5120x2880-rear-spoiler-rear-diffuser-custom-5k-14432.jpg';
import imageFifteen from '../../../images/mercedes-amg-gt-r-3840x2160-2018-4k-11857.jpg';
import imageSixteen from '../../../images/photo_2016-01-13_11-19-37.jpg';
import imageSeventeen from '../../../images/photo_2016-02-15_22-56-03.jpg';
import imageEighteen from '../../../images/photo_2017-07-18_15-24-56.jpg';
import imageNineteen from '../../../images/photo_2017-08-26_12-13-21.jpg';
import imageTwenty from '../../../images/photo_۲۰۱۷-۰۸-۳۰_۱۱-۱۷-۱۱.jpg';
import imageTwentyone from '../../../images/photo_2017-09-07_10-33-15.jpg';
import imageTwentytwo from '../../../images/photo_2017-09-07_10-40-17.jpg';
import imageTwentythree from '../../../images/photo_۲۰۱۷-۱۲-۲۸_۱۱-۵۹-۱۹.jpg';
import imageTwentyfour from '../../../images/photo_۲۰۱۸-۰۴-۰۲_۱۳-۴۴-۴۹.jpg';
import imageTwentyfive from '../../../images/porsche-911-rsr-2880x1800-2017-side-view-4019.jpg';
import imageTwentysix from '../../../images/porsche-panamera-4s-diesel-sport-turismo-2880x1800-2017-6681.jpeg';
import imageTwentyseven from '../../../images/WallpaperStudio10-031207-3840x2160.jpg';
import imageTwentyeight from '../../../images/WallpaperStudio10-133870-3840x2160.jpg';
import imageTwentynine from '../../../images/WallpaperStudio10-161097-1920x1080.jpg';
import imageThirty from '../../../images/00-mercedes-benz-vision-eq-silver-arrow-world-premiere-monterey-car-week-2018-3400x1440.jpg';
import imageThirtyone from '../../../images/01-Mercedes-Benz-G-Class-G-500-4x4-2-Wallpaper-3840x2160.jpg';
import imageThirtytwo from '../../../images/01-mercedes-benz-vehicles-mercedes-amg-gt3-laureus-inspired-by-the-edition-50-auction-c-190-3400x1440.jpg';
import imageThirtythree from '../../../images/6x6-gornos-w.jpg';
import imageThirtyfour from '../../../images/18c0695_001c.jpg';
import imageThirtyfive from '../../../images/1080p-wallpapers-new-HD.png';
import imageThirtysix from '../../../images/93988803_907625239684186_2928864674942205986_n.jpg';
import imageThirtyseven from '../../../images/AAFW1413.png';
import imageThirtyeight from '../../../images/Alfa-Romeo-MiTo-2008-Wallpapers-HD-10.jpg';
import imageThirtynine from '../../../images/american_muscle_camaro-HD.jpg';
import carCover from '../../../images/car_cover.jpg';
import cleaningCloth from '../../../images/cleaning_cloth.jpg';
import seatsCover from '../../../images/seats_cover.jpg';
import floorMats from '../../../images/floor_mats.jpg';
import airFreshener from '../../../images/air_freshener.jpg';
import tireInflator from '../../../images/tire_inflator.jpg';

const initialState = {
   products: {
      vehicles: {
         sedan: [
            { "id": "5qrxMO", "title": "Lincoln", "subtitle": "Mark VIII", "description": "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.", "image": imageOne, "price_detail": { "price": 54826, "discount": 11 }, "rating": { "rate": 38, "count": 743 }, "create_date": 1528922952000, },
            { "id": "zkktsB", "title": "Lexus", "subtitle": "LX", "description": "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.", "image": imageTen, "price_detail": { "price": 54457, "discount": 94 }, "rating": { "rate": 61, "count": 940 }, "create_date": 1615434856000, },
            { "id": "qGDED3", "title": "Hyundai", "subtitle": "Genesis", "description": "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.", "image": imageNineteen, "price_detail": { "price": 8824, "discount": 19 }, "rating": { "rate": 27, "count": 181 }, "create_date": 1253659488000, },
            { "id": "fnlnXT", "title": "Toyota", "subtitle": "Solara", "description": "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.", "image": imageTwentyeight, "price_detail": { "price": 21449, "discount": 0 }, "rating": { "rate": 41, "count": 724 }, "create_date": 1149261033000, },
            { "id": "rSb96T", "title": "Ford", "subtitle": "Thunderbird", "description": "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.", "image": imageThirtyseven, "price_detail": { "price": 81941, "discount": 0 }, "rating": { "rate": 16, "count": 628 }, "create_date": 1372118449000, },
            { "id": "CIh38T", "title": "Chevrolet", "subtitle": "Monte Carlo", "description": "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.", "image": imageSix, "price_detail": { "price": 74853, "discount": 0 }, "rating": { "rate": 49, "count": 4 }, "create_date": 1298247661000, },
         ],
         coupe: [
            { "id": "ciQvs1", "title": "Mercury", "subtitle": "Lynx", "price_detail": { "price": 49575, "discount": 0 }, "description": "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.", "image": imageTwo, "rating": { "rate": 55, "count": 933 }, "create_date": 1042685175000, },
            { "id": "sDzQqe", "title": "Ford", "subtitle": "Econoline E250", "price_detail": { "price": 13267, "discount": 0 }, "description": "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.", "image": imageEleven, "rating": { "rate": 45, "count": 169 }, "create_date": 1384386207000, },
            { "id": "ABKJok", "title": "Chevrolet", "subtitle": "S10", "price_detail": { "price": 32543, "discount": 0 }, "description": "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.", "image": imageTwenty, "rating": { "rate": 42, "count": 958 }, "create_date": 1004058788000, },
            { "id": "tTqtyC", "title": "Chevrolet", "subtitle": "Caprice", "price_detail": { "price": 45757, "discount": 0 }, "description": "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.", "image": imageTwentynine, "rating": { "rate": 44, "count": 268 }, "create_date": 1370300968000, },
            { "id": "KyLC16", "title": "Honda", "subtitle": "Odyssey", "price_detail": { "price": 91306, "discount": 0 }, "description": "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.", "image": imageThirtyeight, "rating": { "rate": 72, "count": 28 }, "create_date": 1550182684000, },
            { "id": "qcjekb", "title": "GMC", "subtitle": "Yukon", "price_detail": { "price": 69479, "discount": 0 }, "description": "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.", "image": imageSeven, "rating": { "rate": 25, "count": 205 }, "create_date": 1611987593000, },
         ],
         sport: [
            { "id": "5fAzF6", "title": "Subaru", "subtitle": "Forester", "price_detail": { "price": 53261, "discount": 0 }, "description": "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.", "image": imageThree, "rating": { "rate": 62, "count": 734 }, "create_date": 1250320810000, },
            { "id": "epmgUU", "title": "Mitsubishi", "subtitle": "Mighty Max Macro", "price_detail": { "price": 71650, "discount": 0 }, "description": "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.", "image": imageTwelve, "rating": { "rate": 52, "count": 740 }, "create_date": 1534726069000, },
            { "id": "PwbwzY", "title": "Honda", "subtitle": "CR-V", "price_detail": { "price": 61214, "discount": 0 }, "description": "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.", "image": imageTwentyone, "rating": { "rate": 61, "count": 605 }, "create_date": 1003124202000, },
            { "id": "Xnt5Aa", "title": "Ford", "subtitle": "Econoline E350", "price_detail": { "price": 71675, "discount": 0 }, "description": "Fusce consequat. Nulla nisl. Nunc nisl.", "image": imageThirty, "rating": { "rate": 92, "count": 274 }, "create_date": 1072452172000, },
            { "id": "oyWYDV", "title": "Buick", "subtitle": "Regal", "price_detail": { "price": 49820, "discount": 42 }, "description": "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.", "image": imageThirtynine, "rating": { "rate": 78, "count": 880 }, "create_date": 1631853775000, },
            { "id": "cJYTar", "title": "Honda", "subtitle": "CR-V", "price_detail": { "price": 1784, "discount": 22 }, "description": "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.", "image": imageEight, "rating": { "rate": 50, "count": 101 }, "create_date": 1241300384000, },
         ],
         station: [
            { "id": "Sih8rA", "title": "Audi", "subtitle": "A6", "price_detail": { "price": 41895, "discount": 0 }, "description": "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.", "image": imageFour, "rating": { "rate": 23, "count": 741 }, "create_date": 1710959289000, },
            { "id": "D1J54I", "title": "Nissan", "subtitle": "Sentra", "price_detail": { "price": 97411, "discount": 0 }, "description": "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.", "image": imageThirteen, "rating": { "rate": 54, "count": 459 }, "create_date": 1503925791000, },
            { "id": "vTS2VA", "title": "Hyundai", "subtitle": "Tucson", "price_detail": { "price": 68449, "discount": 9 }, "description": "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.", "image": imageTwentytwo, "rating": { "rate": 48, "count": 925 }, "create_date": 1488491000000, },
            { "id": "0Pma98", "title": "Lexus", "subtitle": "SC", "price_detail": { "price": 6334, "discount": 0 }, "description": "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.", "image": imageThirtyone, "rating": { "rate": 78, "count": 213 }, "create_date": 1573632112000, },
            { "id": "u4HwtG", "title": "Nissan", "subtitle": "Altima", "price_detail": { "price": 34968, "discount": 0 }, "description": "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.", "image": imageTwentynine, "rating": { "rate": 6, "count": 655 }, "create_date": 1840721560000, },
            { "id": "SUc8dI", "title": "Nissan", "subtitle": "Pathfinder", "price_detail": { "price": 32133, "discount": 0 }, "description": "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.", "image": imageNine, "rating": { "rate": 36, "count": 696 }, "create_date": 1351598941000, },
         ],
         hatchback: [
            { "id": "yonRvz", "title": "Porsche", "subtitle": "928", "price_detail": { "price": 64906, "discount": 21 }, "description": "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.", "image": imageFive, "rating": { "rate": 37, "count": 29 }, "create_date": 1648314962000, },
            { "id": "HSUsIK", "title": "Ford", "subtitle": "Ranger", "price_detail": { "price": 73526, "discount": 83 }, "description": "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.", "image": imageFourteen, "rating": { "rate": 86, "count": 999 }, "create_date": 1363006067000, },
            { "id": "6kmD7u", "title": "Volkswagen", "subtitle": "New Beetle", "price_detail": { "price": 88077, "discount": 96 }, "description": "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.", "image": imageTwentythree, "rating": { "rate": 95, "count": 919 }, "create_date": 1619709958000, },
            { "id": "wrnSv4", "title": "Volvo", "subtitle": "S90", "price_detail": { "price": 20921, "discount": 49 }, "description": "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.", "image": imageThirtytwo, "rating": { "rate": 81, "count": 619 }, "create_date": 1193956950000, },
            { "id": "C44Jow", "title": "Nissan", "subtitle": "Rogue", "price_detail": { "price": 87760, "discount": 0 }, "description": "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.", "image": imageOne, "rating": { "rate": 24, "count": 378 }, "create_date": 1310898284000, },
            { "id": "W77cdV", "title": "Mitsubishi", "subtitle": "GTO", "price_detail": { "price": 72022, "discount": 0 }, "description": "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.", "image": imageTwo, "rating": { "rate": 61, "count": 417 }, "create_date": 1679017133000, }
         ],
         convertible: [
            { "id": "A82l6f", "title": "Dodge", "subtitle": "Caravan", "price_detail": { "price": 84848, "discount": 0 }, "description": "Sed ante. Vivamus tortor. Duis mattis egestas metus.", "image": imageSix, "rating": { "rate": 59, "count": 985 }, "create_date": 1354257738000, },
            { "id": "sN0vZK", "title": "Ford", "subtitle": "Freestar", "price_detail": { "price": 40704, "discount": 0 }, "description": "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.", "image": imageFifteen, "rating": { "rate": 19, "count": 621 }, "create_date": 1171397055000, },
            { "id": "6ajJse", "title": "Pontiac", "subtitle": "Firefly", "price_detail": { "price": 94329, "discount": 0 }, "description": "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.", "image": imageTwentyfour, "rating": { "rate": 21, "count": 220 }, "create_date": 1376231866000, },
            { "id": "dntoVk", "title": "Volvo", "subtitle": "XC70", "price_detail": { "price": 60742, "discount": 76 }, "description": "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.", "image": imageThirtythree, "rating": { "rate": 49, "count": 100 }, "create_date": 1370921255000, },
            { "id": "SPc3uX", "title": "Buick", "subtitle": "Century", "price_detail": { "price": 83716, "discount": 0 }, "description": "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.", "image": imageTwo, "rating": { "rate": 78, "count": 261 }, "create_date": 1273009468000, },
         ],
         suv: [
            { "id": "o2gCno", "title": "Kia", "subtitle": "Optima", "price_detail": { "price": 80778, "discount": 0 }, "description": "In congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.", "image": imageSeven, "rating": { "rate": 47, "count": 370 }, "create_date": 1013048835000, },
            { "id": "MJ4M1w", "title": "Saab", "subtitle": "9-5", "price_detail": { "price": 31324, "discount": 60 }, "description": "In congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.", "image": imageSixteen, "rating": { "rate": 59, "count": 905 }, "create_date": 1854383618000, },
            { "id": "pZIp37", "title": "Audi", "subtitle": "A4", "price_detail": { "price": 99617, "discount": 4 }, "description": "Fusce consequat. Nulla nisl. Nunc nisl.", "image": imageTwentyfive, "rating": { "rate": 99, "count": 425 }, "create_date": 1527872174000, },
            { "id": "f8Fg3z", "title": "Mazda", "subtitle": "MX-3", "price_detail": { "price": 71112, "discount": 0 }, "description": "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.", "image": imageThirtyfour, "rating": { "rate": 16, "count": 433 }, "create_date": 1155759835000, },
            { "id": "6PtFeV", "title": "Chevrolet", "subtitle": "Corvette", "price_detail": { "price": 86737, "discount": 0 }, "description": "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.", "image": imageThree, "rating": { "rate": 76, "count": 544 }, "create_date": 1843014136000, },
         ],
         minivan: [
            { "id": "igBqqJ", "title": "Mercury", "subtitle": "Cougar", "price_detail": { "price": 88015, "discount": 27 }, "description": "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.", "image": imageEight, "rating": { "rate": 77, "count": 487 }, "create_date": 1307304005000, },
            { "id": "ZXjFwa", "title": "Lincoln", "subtitle": "Town Car", "price_detail": { "price": 77170, "discount": 0 }, "description": "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.", "image": imageSeventeen, "rating": { "rate": 51, "count": 221 }, "create_date": 1609665384000, },
            { "id": "si4CDB", "title": "Pontiac", "subtitle": "Grand Prix", "price_detail": { "price": 59275, "discount": 48 }, "description": "Sed ante. Vivamus tortor. Duis mattis egestas metus.", "image": imageTwentysix, "rating": { "rate": 19, "count": 76 }, "create_date": 1468027604000, },
            { "id": "RijilK", "title": "Lincoln", "subtitle": "MKX", "price_detail": { "price": 14334, "discount": 42 }, "description": "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.", "image": imageThirtyfive, "rating": { "rate": 81, "count": 378 }, "create_date": 1199059324000, },
            { "id": "3VVRRd", "title": "Mercedes-Benz", "subtitle": "M-Class", "price_detail": { "price": 50128, "discount": 0 }, "description": "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.", "image": imageFour, "rating": { "rate": 89, "count": 677 }, "create_date": 1546701185000, },
         ],
         pickup_truck: [
            { "id": "LFEBu5", "title": "Audi", "subtitle": "5000S", "price_detail": { "price": 31367, "discount": 0 }, "description": "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.", "image": imageNine, "rating": { "rate": 99, "count": 285 }, "create_date": 1809743793000, },
            { "id": "bpE8rG", "title": "Subaru", "subtitle": "Forester", "price_detail": { "price": 55462, "discount": 0 }, "description": "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.", "image": imageEighteen, "rating": { "rate": 90, "count": 649 }, "create_date": 1568338087000, },
            { "id": "CcUjN5", "title": "Mazda", "subtitle": "CX-7", "price_detail": { "price": 23807, "discount": 0 }, "description": "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.", "image": imageTwentyseven, "rating": { "rate": 4, "count": 205 }, "create_date": 987872597000, },
            { "id": "QRfCjJ", "title": "Smart", "subtitle": "Fortwo", "price_detail": { "price": 64030, "discount": 0 }, "description": "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.", "image": imageThirtysix, "rating": { "rate": 56, "count": 310 }, "create_date": 1652744383000, },
            { "id": "09P3V4", "title": "Mitsubishi", "subtitle": "Montero Sport", "price_detail": { "price": 82770, "discount": 95 }, "description": "Fusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.", "image": imageFive, "rating": { "rate": 38, "count": 290 }, "create_date": 1054885439000, },
         ],
      },
      accessories: {
         car_cover: [
            { "id": "jpZ9Pl", "title": "روکش خودرو مدل C0L مناسب برای پژو 405 و پرشیا و سمند و 206SD و رانا", "subtitle": "sodales sed", "description": "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.", "rating": { "rate": 87, "count": 208 }, "price_detail": { "price": 266, "discount": 18, }, "image": carCover, "create_date": 1787296291000, },
            { "id": "X5kOyq", "title": "چادر خودرو مدل 028", "subtitle": "risus semper", "description": "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", "rating": { "rate": 68, "count": 668 }, "price_detail": { "price": 522, "discount": 31, }, "image": carCover, "create_date": 1367756182000, },
            { "id": "LMt0WM", "title": "چادر اتوماتیک خودرو کد AM64", "subtitle": "at", "description": "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.", "rating": { "rate": 60, "count": 396 }, "price_detail": { "price": 509, "discount": 82, }, "image": carCover, "create_date": 1479650802000, },
            { "id": "ALjuOG", "title": "روکش خودرو مدل کارمن کد 002", "subtitle": "quam", "description": "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.", "rating": { "rate": 60, "count": 678 }, "price_detail": { "price": 914, "discount": 78, }, "image": carCover, "create_date": 1184205386000, },
            { "id": "UH07KO", "title": "روکش خودرو مناسب برای پرایدصبا تیبا 1 تیبا 2 پراید 111 پراید 132 پراید 131", "subtitle": "lectus in quam", "description": "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.", "rating": { "rate": 99, "count": 482 }, "price_detail": { "price": 911, "discount": 84, }, "image": carCover, "create_date": 1406694504000, },
            { "id": "L6df4O", "title": "روکش خودرو مدل C0M مناسب برای پراید و پژو 206 هاچبک و تیبا و هیوندای i20", "subtitle": "eu nibh quisque", "description": "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.", "rating": { "rate": 58, "count": 768 }, "price_detail": { "price": 899, "discount": 1, }, "image": carCover, "create_date": 947633690000, },
            { "id": "nEBj5N", "title": "چادر خودرو مدل پنبه ای", "subtitle": "vivamus", "description": "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.", "rating": { "rate": 55, "count": 990 }, "price_detail": { "price": 871, "discount": 88, }, "image": carCover, "create_date": 992667914000, },
            { "id": "ZyeJUM", "title": "چادر خودرو رویال اسپرت مدل UV RESISTANT مناسب برای پژو 206", "subtitle": "volutpat", "description": "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.", "rating": { "rate": 35, "count": 104 }, "price_detail": { "price": 486, "discount": 70, }, "image": carCover, "create_date": 1198357991000, },
            { "id": "G7aAJa", "title": "چادر خودرو مدل 031", "subtitle": "est quam pharetra", "description": "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.", "rating": { "rate": 32, "count": 658 }, "price_detail": { "price": 100, "discount": 89, }, "image": carCover, "create_date": 1539830682000, },
            { "id": "7q1POj", "title": "روکش خودرو بابل کارپت مدل LT1 مناسب برای پژو پارس", "subtitle": "habitasse platea", "description": "Phasellus in felis. Donec semper sapien a libero. Nam dui.", "rating": { "rate": 62, "count": 23 }, "price_detail": { "price": 119, "discount": 36, }, "image": carCover, "create_date": 1703156821000, },
            { "id": "AOcA6a", "title": "چادر خودرو رویال اسپرت مدل UV RESISTANT مناسب برای پژو 405", "subtitle": "nulla", "description": "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.", "rating": { "rate": 26, "count": 542 }, "price_detail": { "price": 515, "discount": 68, }, "image": carCover, "create_date": 1069503681000, },
            { "id": "GKj3zo", "title": "چادر خودرو رویال اسپرت مدل UV RESISTANT مناسب برای پراید", "subtitle": "pellentesque ultrices mattis", "description": "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.", "rating": { "rate": 0, "count": 615 }, "price_detail": { "price": 112, "discount": 78, }, "image": carCover, "create_date": 1243443875000, },
            { "id": "dNhWnM", "title": "روکش خودرو ساکا مدل SOL مناسب برای پژو پارس", "subtitle": "in", "description": "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.", "rating": { "rate": 63, "count": 634 }, "price_detail": { "price": 411, "discount": 86, }, "image": carCover, "create_date": 1364451298000, },
            { "id": "hzPrx5", "title": "چادر خودرو رویال اسپرت مدل BE مناسب برای دنا پلاس", "subtitle": "nec", "description": "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.", "rating": { "rate": 86, "count": 297 }, "price_detail": { "price": 362, "discount": 38, }, "image": carCover, "create_date": 1196999267000, },
            { "id": "7dORHC", "title": "چادر خودرو رویال اسپرت مدل UV RESISTANT مناسب برای سمند", "subtitle": "nam", "description": "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.", "rating": { "rate": 9, "count": 565 }, "price_detail": { "price": 986, "discount": 84, }, "image": carCover, "create_date": 1079434939000, },
         ],
         cleaning_cloth: [
            { "id": "9pYEnB", "title": "دستمال تمیز کننده نانو وورث مدل 899900106", "subtitle": "nec sem duis", "description": "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.", "rating": { "rate": 78, "count": 489, }, "price_detail": { "price": 385000, "discount": 0, }, "image": cleaningCloth, "create_date": 1317077678000, },
            { "id": "rOyfA2", "title": "دستمال میکروفایبر نظافت خودرو مدل WHE2", "subtitle": "ut", "description": "Phasellus in felis. Donec semper sapien a libero. Nam dui.", "rating": { "rate": 66, "count": 1807, }, "price_detail": { "price": 93000, "discount": 10, }, "image": cleaningCloth, "create_date": 1380791790000, },
            { "id": "1F9V9b", "title": "دستمال حوله ای مایکروفایبر ضدخش تام کلین مدل Mfl300s", "subtitle": "est risus auctor", "description": "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.", "rating": { "rate": 84, "count": 4369, }, "price_detail": { "price": 275000, "discount": 15, }, "image": cleaningCloth, "create_date": 1163945951000, },
            { "id": "Pekiq6", "title": "دستمال میکروفایبر نظافت خودرو تام کلین مدل TC-MFL450A", "subtitle": "aliquam", "description": "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.", "rating": { "rate": 86, "count": 735, }, "price_detail": { "price": 475000, "discount": 5, }, "image": cleaningCloth, "create_date": 1155817652000, },
            { "id": "8FWwux", "title": " اسفنج نظافت خودرو مدل GTW", "subtitle": "luctus", "description": "In congue. Etiam justo. Etiam pretium iaculis justo.", "rating": { "rate": 82, "count": 2809, }, "price_detail": { "price": 93800, "discount": 0, }, "image": cleaningCloth, "create_date": 983441910000, },
            { "id": "ESN3md", "title": "تیغه شیشه پاک کن کد CL-01", "subtitle": "tincidunt", "description": "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.", "rating": { "rate": 80, "count": 671, }, "price_detail": { "price": 139000, "discount": 0, }, "image": cleaningCloth, "create_date": 1783918761000, },
            { "id": "uNnSUl", "title": "پد پولیش تیوان  مدل  YP115", "subtitle": "eget eros", "description": "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.", "rating": { "rate": 80, "count": 36, }, "price_detail": { "price": 320000, "discount": 0, }, "image": cleaningCloth, "create_date": 979454173000, },
            { "id": "muppHJ", "title": "تیغه شیشه پاک کن ابر و اسپری دار  دی ان دی مدل TSPA", "subtitle": "sapien sapien", "description": "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.", "rating": { "rate": 76, "count": 508, }, "price_detail": { "price": 398000, "discount": 0, }, "image": cleaningCloth, "create_date": 1132436561000, },
            { "id": "Ky5qt3", "title": "لنگ یزدی مدل W-2 بسته 2 عددی", "subtitle": "erat", "description": "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.", "rating": { "rate": 58, "count": 36, }, "price_detail": { "price": 203000, "discount": 0, }, "image": cleaningCloth, "create_date": 1147336904000, },
            { "id": "9HRftk", "title": "دستمال نظافت خودرو وایت اند وایت مدل W_01 بسته 4 عددی", "subtitle": "ac diam", "description": "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.", "rating": { "rate": 60, "count": 3, }, "price_detail": { "price": 3800000, "discount": 0, }, "image": cleaningCloth, "create_date": 1175323400000, },
            { "id": "wJ0qbT", "title": "دستمال جادویی مارپا", "subtitle": "donec", "description": "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.", "rating": { "rate": 72, "count": 156, }, "price_detail": { "price": 400000, "discount": 0, }, "image": cleaningCloth, "create_date": 1538740716000, },
            { "id": "DpIbbZ", "title": "اسفنج شستشوی خودرو هانسه طرح مخملی مدل نانو", "subtitle": "massa id lobortis", "description": "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.", "rating": { "rate": 84, "count": 351, }, "price_detail": { "price": 227000, "discount": 0, }, "image": cleaningCloth, "create_date": 1819336872000, },
            { "id": "GElX2U", "title": "لنگ مدل نسیم کد B31", "subtitle": "donec ut dolor", "description": "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.", "rating": { "rate": 80, "count": 33, }, "price_detail": { "price": 350000, "discount": 0, }, "image": cleaningCloth, "create_date": 1051673961000, },
            { "id": "HvArkO", "title": " دستمال میکروفایبر نظافت خودرو تاپ کلین مدل 6412 بسته 5عددی", "subtitle": "nam tristique tortor", "description": "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.", "rating": { "rate": 68, "count": 73, }, "price_detail": { "price": 450000, "discount": 18, }, "image": cleaningCloth, "create_date": 1235060003000, },
            { "id": "0CIyZs", "title": "تیغه شیشه پاک کن خودرو ارج پلاستیک مدل ۱۷۸", "subtitle": "tortor id nulla", "description": "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.", "rating": { "rate": 76, "count": 412, }, "price_detail": { "price": 135000, "discount": 0, }, "image": cleaningCloth, "create_date": 1042079357000, },
            { "id": "q6QP4K", "title": "اسفنج خش گیر خودرو تام کلین مدل TC-RB120N72", "subtitle": "iaculis diam", "description": "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.", "rating": { "rate": 74, "count": 52, }, "price_detail": { "price": 272000, "discount": 14, }, "image": cleaningCloth, "create_date": 1103533767000, },
            { "id": "NfwPla", "title": "لنگ یزدی مدل R-2 سایز متوسط بسته 2 عددی", "subtitle": "phasellus", "description": "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.", "rating": { "rate": 62, "count": 2923, }, "price_detail": { "price": 120500, "discount": 0, }, "image": cleaningCloth, "create_date": 1735606281000, },
            { "id": "0lwJ0K", "title": "دستمال میکروفایبر نظافت خودرو اینجوی هاوس مدل HW6 بسته 6 عددی", "subtitle": "a feugiat et", "description": "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.", "rating": { "rate": 74, "count": 125, }, "price_detail": { "price": 459000, "discount": 33, }, "image": cleaningCloth, "create_date": 1870200040000, },
            { "id": "lH87XM", "title": "دستمال میکرو اکتیو و نانو وورث مدل 899900106", "subtitle": "tortor", "description": "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.", "rating": { "rate": 84, "count": 46, }, "price_detail": { "price": 485000, "discount": 0, }, "image": cleaningCloth, "create_date": 1367878389000, },
            { "id": "uVhYiA", "title": "حوله خشک کننده میکروفایبر ممتاز تام کلین مدل Tc-MFL400a", "subtitle": "mauris", "description": "Phasellus in felis. Donec semper sapien a libero. Nam dui.", "rating": { "rate": 84, "count": 1175, }, "price_detail": { "price": 425000, "discount": 0, }, "image": cleaningCloth, "create_date": 1409508391000, },
         ],
         seats_cover: [
            { "id": "tt96uk", "title": "روکش صندلی خودرو مدل 2002 مناسب برای پراید صبا", "subtitle": "pellentesque", "description": "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.", "price_detail": { "price": 2100000, "discount": 0 }, "rating": { "rate": 64, "count": 462 }, "image": seatsCover, "create_date": 1051519067000, },
            { "id": "NZo0vD", "title": "روکش صندلی خودرو مدل 4004 مناسب برای پراید", "subtitle": "donec pharetra", "description": "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.", "price_detail": { "price": 2950000, "discount": 0 }, "rating": { "rate": 66, "count": 235 }, "image": seatsCover, "create_date": 1256494279000, },
            { "id": "TG9cEo", "title": "روکش صندلی خودرو سوشیانت مدل S-30 مناسب برای پژو 206", "subtitle": "duis", "description": "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.", "price_detail": { "price": 10200000, "discount": 15 }, "rating": { "rate": 76, "count": 3 }, "image": seatsCover, "create_date": 1634516182000, },
            { "id": "yEnMPA", "title": "روکش صندلی خودرو مدل 2006 مناسب برای سمند", "subtitle": "lacinia aenean sit", "description": "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.", "price_detail": { "price": 3350000, "discount": 0 }, "rating": { "rate": 68, "count": 21 }, "image": seatsCover, "create_date": 1122682839000, },
            { "id": "8vJvAQ", "title": "روکش صندلی خودرو مدل 205 مناسب برای پراید 131", "subtitle": "vel est donec", "description": "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.", "price_detail": { "price": 2300000, "discount": 0 }, "rating": { "rate": 58, "count": 50 }, "image": seatsCover, "create_date": 1290102084000, },
            { "id": "577Eha", "title": "روکش صندلی خودرو مدل 1019 مناسب برای پژو 405", "subtitle": "commodo vulputate justo", "description": "In congue. Etiam justo. Etiam pretium iaculis justo.", "price_detail": { "price": 2990000, "discount": 0 }, "rating": { "rate": 68, "count": 100 }, "image": seatsCover, "create_date": 1573679946000, },
            { "id": "axizx1", "title": "روکش صندلی خودرو مدل SAR003 مناسب برای پراید 131", "subtitle": "accumsan tortor", "description": "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.", "price_detail": { "price": 4792200, "discount": 2 }, "rating": { "rate": 64, "count": 23 }, "image": seatsCover, "create_date": 1610582765000, },
            { "id": "hhuEns", "title": "روکش صندلی خودرو مدل Sar00Fp مناسب برای پراید صبا", "subtitle": "pharetra magna", "description": "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.", "price_detail": { "price": 3300000, "discount": 0 }, "rating": { "rate": 44, "count": 6 }, "image": seatsCover, "create_date": 1696063228000, },
            { "id": "1xj7ux", "title": "روکش صندلی خودرو مدل بایکو مناسب برای پژو پارس", "subtitle": "id mauris vulputate", "description": "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.", "price_detail": { "price": 8300000, "discount": 0 }, "rating": { "rate": 74, "count": 9 }, "image": seatsCover, "create_date": 1108745430000, },
            { "id": "IchoVL", "title": "روکش صندلی خودرو کد 222 مناسب برای پراید صبا", "subtitle": "id sapien", "description": "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.", "price_detail": { "price": 5390000, "discount": 0 }, "rating": { "rate": 84, "count": 75 }, "image": seatsCover, "create_date": 1687322359000, },
            { "id": "FZcTfR", "title": "روکش صندلی خودرو مدل 1602 مناسب برای تیبا", "subtitle": "curae nulla", "description": "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.", "price_detail": { "price": 2950000, "discount": 0 }, "rating": { "rate": 66, "count": 75 }, "image": seatsCover, "create_date": 1724937384000, },
            { "id": "C1LqxA", "title": "روکش صندلی خودرو هایکو مدل کتیبه مناسب برای پژو پارس", "subtitle": "sapien cum", "description": "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.", "price_detail": { "price": 11490000, "discount": 0 }, "rating": { "rate": 88, "count": 76 }, "image": seatsCover, "create_date": 1888127924000, },
            { "id": "E5av2C", "title": "روکش صندلی خودرو مدل 1001 مناسب برای پراید", "subtitle": "volutpat erat", "description": "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.", "price_detail": { "price": 2140000, "discount": 0 }, "rating": { "rate": 66, "count": 43 }, "image": seatsCover, "create_date": 1591906118000, },
            { "id": "o8JX9p", "title": "روکش صندلی خودرو مدل 2001 مناسب برای پژو 405", "subtitle": "platea", "description": "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", "price_detail": { "price": 2050000, "discount": 0 }, "rating": { "rate": 60, "count": 113 }, "image": seatsCover, "create_date": 973907083000, },
            { "id": "Q7lADH", "title": "روکش صندلی خودرو آذین روکش مدل AZ208 مناسب برای تیبا 2 و کوییک", "subtitle": "hac habitasse", "description": "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.", "price_detail": { "price": 7830200, "discount": 2 }, "rating": { "rate": 20, "count": 2 }, "image": seatsCover, "create_date": 1512146326000, },
            { "id": "WTWoXT", "title": "روکش صندلی خودرو مدل بایکو مناسب برای پژو 206", "subtitle": "erat quisque", "description": "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.", "price_detail": { "price": 8300000, "discount": 0 }, "rating": { "rate": 76, "count": 18 }, "image": seatsCover, "create_date": 1638403841000, },
            { "id": "qxLt7S", "title": "روکش صندلی خودرو آذین روکش مدل AZ214 مناسب برای پژو 405 و پژو پارس", "subtitle": "viverra", "description": "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", "price_detail": { "price": 7830200, "discount": 2 }, "rating": { "rate": 28, "count": 2 }, "image": seatsCover, "create_date": 1101686631000, },
            { "id": "88NCbq", "title": "روکش صندلی خودرو کد َD_3 مناسب برای دنا", "subtitle": "ut massa volutpat", "description": "In congue. Etiam justo. Etiam pretium iaculis justo.", "price_detail": { "price": 9900000, "discount": 0 }, "rating": { "rate": 80, "count": 14 }, "image": seatsCover, "create_date": 1697730379000, },
            { "id": "V7iHpn", "title": "روکش صندلی خودرو جلوه مدل PR13 مناسب برای پژو پارس", "subtitle": "dictumst aliquam", "description": "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.", "price_detail": { "price": 11900000, "discount": 0 }, "rating": { "rate": 0, "count": 0 }, "image": seatsCover, "create_date": 947938797000, },
            { "id": "zbesvW", "title": "روکش صندلی خودرو هایکو مدل سارینا مناسب برای سمند", "subtitle": "cursus", "description": "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.", "price_detail": { "price": 9600000, "discount": 0 }, "rating": { "rate": 80, "count": 72 }, "image": seatsCover, "create_date": 1803712345000, },
         ],
         floor_mats: [
            { "id": "vp63Bg", "title": "vivamus vestibulum sagittis", "subtitle": "proin at", "description": "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.", "price_detail": { "price": 669873, "discount": 20 }, "rating": { "rate": 51, "count": 238 }, "image": floorMats, "create_date": 1692765014000, },
            { "id": "6BtzcE", "title": "eget", "subtitle": "sapien varius", "description": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.", "price_detail": { "price": 993428, "discount": 4 }, "rating": { "rate": 86, "count": 90 }, "image": floorMats, "create_date": 1284080779000, },
            { "id": "eQLgZZ", "title": "sit amet", "subtitle": "aliquam non mauris", "description": "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.", "price_detail": { "price": 856468, "discount": 16 }, "rating": { "rate": 19, "count": 141 }, "image": floorMats, "create_date": 1214335276000, },
            { "id": "YHcDac", "title": "eget eleifend luctus", "subtitle": "accumsan odio curabitur", "description": "In congue. Etiam justo. Etiam pretium iaculis justo.", "price_detail": { "price": 759533, "discount": 66 }, "rating": { "rate": 41, "count": 54 }, "image": floorMats, "create_date": 1315822976000, },
            { "id": "xIP4vb", "title": "libero nullam sit", "subtitle": "libero", "description": "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.", "price_detail": { "price": 61592, "discount": 15 }, "rating": { "rate": 88, "count": 295 }, "image": floorMats, "create_date": 1069842234000, },
            { "id": "7CHWXJ", "title": "curabitur", "subtitle": "ac neque", "description": "Fusce consequat. Nulla nisl. Nunc nisl.", "price_detail": { "price": 441510, "discount": 71 }, "rating": { "rate": 38, "count": 102 }, "image": floorMats, "create_date": 1688286222000, },
            { "id": "DERXul", "title": "nec", "subtitle": "iaculis congue vivamus", "description": "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.", "price_detail": { "price": 48875, "discount": 56 }, "rating": { "rate": 91, "count": 191 }, "image": floorMats, "create_date": 1630293395000, },
            { "id": "ZBOblB", "title": "in magna bibendum", "subtitle": "varius", "description": "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.", "price_detail": { "price": 27741, "discount": 36 }, "rating": { "rate": 35, "count": 56 }, "image": floorMats, "create_date": 1778497539000, },
            { "id": "ZsaI52", "title": "at turpis", "subtitle": "non lectus", "description": "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.", "price_detail": { "price": 998030, "discount": 6 }, "rating": { "rate": 73, "count": 69 }, "image": floorMats, "create_date": 1740681988000, },
            { "id": "IMkoRZ", "title": "volutpat quam pede", "subtitle": "sapien", "description": "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.", "price_detail": { "price": 445879, "discount": 48 }, "rating": { "rate": 42, "count": 291 }, "image": floorMats, "create_date": 1681677404000, },
            { "id": "S7J7Gy", "title": "in consequat", "subtitle": "adipiscing elit proin", "description": "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.", "price_detail": { "price": 196899, "discount": 10 }, "rating": { "rate": 54, "count": 188 }, "image": floorMats, "create_date": 1622999508000, },
            { "id": "sI7NzE", "title": "feugiat et", "subtitle": "dapibus duis", "description": "In congue. Etiam justo. Etiam pretium iaculis justo.", "price_detail": { "price": 930861, "discount": 43 }, "rating": { "rate": 87, "count": 293 }, "image": floorMats, "create_date": 1101802927000, },
            { "id": "lzMNiU", "title": "dictumst etiam", "subtitle": "justo", "description": "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.", "price_detail": { "price": 326854, "discount": 24 }, "rating": { "rate": 19, "count": 239 }, "image": floorMats, "create_date": 1601698034000, },
            { "id": "c7Ap9F", "title": "at feugiat non", "subtitle": "eget eleifend luctus", "description": "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.", "price_detail": { "price": 303319, "discount": 14 }, "rating": { "rate": 43, "count": 92 }, "image": floorMats, "create_date": 1373453848000, },
            { "id": "RCkVby", "title": "sociis natoque", "subtitle": "convallis eget", "description": "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.", "price_detail": { "price": 329044, "discount": 34 }, "rating": { "rate": 11, "count": 271 }, "image": floorMats, "create_date": 1128098431000, },
            { "id": "2l7aBi", "title": "potenti", "subtitle": "ante ipsum primis", "description": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.", "price_detail": { "price": 958881, "discount": 64 }, "rating": { "rate": 35, "count": 75 }, "image": floorMats, "create_date": 1020926811000, },
            { "id": "T7ItBe", "title": "condimentum id luctus", "subtitle": "auctor sed", "description": "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", "price_detail": { "price": 390357, "discount": 15 }, "rating": { "rate": 64, "count": 224 }, "image": floorMats, "create_date": 1471521646000, },
            { "id": "8UZfPy", "title": "phasellus", "subtitle": "consequat", "description": "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", "price_detail": { "price": 960916, "discount": 95 }, "rating": { "rate": 28, "count": 283 }, "image": floorMats, "create_date": 1057556318000, },
            { "id": "9E9JC8", "title": "vestibulum ante", "subtitle": "eu", "description": "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.", "price_detail": { "price": 597910, "discount": 65 }, "rating": { "rate": 57, "count": 113 }, "image": floorMats, "create_date": 1632905477000, },
            { "id": "dDZIBU", "title": "sed vestibulum", "subtitle": "convallis", "description": "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.", "price_detail": { "price": 665603, "discount": 30 }, "rating": { "rate": 47, "count": 128 }, "image": floorMats, "create_date": 1775284546000, },
         ],
         air_freshener: [
            { "id": "x9d2XQ", "title": "nullam", "subtitle": "penatibus et magnis", "description": "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.", "price_detail": { "price": 221048, "discount": 71 }, "rating": { "rate": 1, "count": 287 }, "image": airFreshener, "create_date": 1712786257000, },
            { "id": "JGr2kx", "title": "nulla pede ullamcorper", "subtitle": "lorem", "description": "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.", "price_detail": { "price": 976169, "discount": 89 }, "rating": { "rate": 83, "count": 84 }, "image": airFreshener, "create_date": 981741674000, },
            { "id": "UdomPl", "title": "nulla suscipit ligula", "subtitle": "varius integer ac", "description": "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.", "price_detail": { "price": 251760, "discount": 91 }, "rating": { "rate": 28, "count": 83 }, "image": airFreshener, "create_date": 1728534137000, },
            { "id": "kCcI4i", "title": "turpis nec euismod", "subtitle": "ut erat", "description": "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.", "price_detail": { "price": 944183, "discount": 75 }, "rating": { "rate": 85, "count": 167 }, "image": airFreshener, "create_date": 1652169106000, },
            { "id": "6Lt4dH", "title": "primis", "subtitle": "ante vestibulum", "description": "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.", "price_detail": { "price": 368996, "discount": 1 }, "rating": { "rate": 59, "count": 112 }, "image": airFreshener, "create_date": 1403155486000, },
            { "id": "ZpLK18", "title": "faucibus cursus", "subtitle": "sit amet nunc", "description": "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.", "price_detail": { "price": 126407, "discount": 36 }, "rating": { "rate": 77, "count": 130 }, "image": airFreshener, "create_date": 1897161303000, },
            { "id": "A0ixf3", "title": "congue risus", "subtitle": "augue", "description": "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.", "price_detail": { "price": 934960, "discount": 60 }, "rating": { "rate": 62, "count": 93 }, "image": airFreshener, "create_date": 1631925974000, },
            { "id": "QQ9ngs", "title": "sed tincidunt", "subtitle": "sapien arcu", "description": "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.", "price_detail": { "price": 242298, "discount": 31 }, "rating": { "rate": 70, "count": 20 }, "image": airFreshener, "create_date": 1887255798000, },
            { "id": "poU74e", "title": "libero nullam", "subtitle": "enim sit", "description": "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.", "price_detail": { "price": 226104, "discount": 57 }, "rating": { "rate": 12, "count": 0 }, "image": airFreshener, "create_date": 1218825989000, },
            { "id": "TCCVa9", "title": "ligula", "subtitle": "libero convallis eget", "description": "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.", "price_detail": { "price": 383392, "discount": 33 }, "rating": { "rate": 50, "count": 224 }, "image": airFreshener, "create_date": 1368086635000, },
            { "id": "g70ecM", "title": "orci luctus et", "subtitle": "sapien dignissim", "description": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.", "price_detail": { "price": 467767, "discount": 88 }, "rating": { "rate": 94, "count": 65 }, "image": airFreshener, "create_date": 1879443944000, },
            { "id": "bKE9nB", "title": "consequat in consequat", "subtitle": "pharetra", "description": "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.", "price_detail": { "price": 189553, "discount": 32 }, "rating": { "rate": 30, "count": 142 }, "image": airFreshener, "create_date": 1035911886000, },
            { "id": "vlPtHd", "title": "massa id lobortis", "subtitle": "laoreet ut", "description": "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.", "price_detail": { "price": 738747, "discount": 46 }, "rating": { "rate": 49, "count": 65 }, "image": airFreshener, "create_date": 1330254995000, },
            { "id": "IPfPWS", "title": "ante vivamus tortor", "subtitle": "ultrices enim lorem", "description": "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.", "price_detail": { "price": 988978, "discount": 72 }, "rating": { "rate": 35, "count": 43 }, "image": airFreshener, "create_date": 1631577064000, },
            { "id": "yWrqel", "title": "vel augue", "subtitle": "eget", "description": "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.", "price_detail": { "price": 504623, "discount": 13 }, "rating": { "rate": 77, "count": 187 }, "image": airFreshener, "create_date": 1732853414000, },
            { "id": "ggXCk8", "title": "nulla", "subtitle": "justo sollicitudin ut", "description": "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.", "price_detail": { "price": 586057, "discount": 84 }, "rating": { "rate": 50, "count": 182 }, "image": airFreshener, "create_date": 954664879000, },
            { "id": "ONtEdo", "title": "suspendisse ornare consequat", "subtitle": "enim leo", "description": "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.", "price_detail": { "price": 924568, "discount": 82 }, "rating": { "rate": 47, "count": 7 }, "image": airFreshener, "create_date": 1744675780000, },
            { "id": "lx2HeI", "title": "nisl nunc", "subtitle": "nulla tempus", "description": "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.", "price_detail": { "price": 794150, "discount": 78 }, "rating": { "rate": 44, "count": 295 }, "image": airFreshener, "create_date": 1124536701000, },
            { "id": "HHN4u2", "title": "et ultrices posuere", "subtitle": "scelerisque", "description": "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.", "price_detail": { "price": 100963, "discount": 26 }, "rating": { "rate": 99, "count": 222 }, "image": airFreshener, "create_date": 1746389429000, },
            { "id": "IggJwU", "title": "potenti in", "subtitle": "ante ipsum", "description": "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.", "price_detail": { "price": 972002, "discount": 35 }, "rating": { "rate": 72, "count": 98 }, "image": airFreshener, "create_date": 1914513345000, },
         ],
         tire_inflator: [
            { "id": "lVkTjC", "title": "eros vestibulum", "subtitle": "interdum in", "description": "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.", "price_detail": { "price": 510074, "discount": 61 }, "rating": { "rate": 27, "count": 159 }, "image": tireInflator, "create_date": 978586539000, },
            { "id": "cUEQQx", "title": "in felis", "subtitle": "justo maecenas rhoncus", "description": "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.", "price_detail": { "price": 171917, "discount": 61 }, "rating": { "rate": 88, "count": 251 }, "image": tireInflator, "create_date": 1016207242000, },
            { "id": "pIqQJ6", "title": "luctus cum sociis", "subtitle": "ultrices mattis odio", "description": "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.", "price_detail": { "price": 214225, "discount": 22 }, "rating": { "rate": 1, "count": 130 }, "image": tireInflator, "create_date": 1517141641000, },
            { "id": "HpUA96", "title": "maecenas rhoncus", "subtitle": "gravida sem praesent", "description": "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.", "price_detail": { "price": 302281, "discount": 77 }, "rating": { "rate": 40, "count": 180 }, "image": tireInflator, "create_date": 1300450361000, },
            { "id": "kSwXQH", "title": "quam", "subtitle": "potenti in", "description": "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.", "price_detail": { "price": 583961, "discount": 98 }, "rating": { "rate": 96, "count": 292 }, "image": tireInflator, "create_date": 1150951254000, },
            { "id": "pF5DLT", "title": "purus aliquet", "subtitle": "sed", "description": "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.", "price_detail": { "price": 521639, "discount": 64 }, "rating": { "rate": 51, "count": 265 }, "image": tireInflator, "create_date": 1400324955000, },
            { "id": "GvM0YJ", "title": "justo etiam pretium", "subtitle": "quisque", "description": "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", "price_detail": { "price": 725390, "discount": 10 }, "rating": { "rate": 32, "count": 72 }, "image": tireInflator, "create_date": 1435886585000, },
            { "id": "hj7Izg", "title": "pellentesque", "subtitle": "sem", "description": "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", "price_detail": { "price": 261370, "discount": 68 }, "rating": { "rate": 62, "count": 239 }, "image": tireInflator, "create_date": 1820355474000, },
            { "id": "7Ljkuk", "title": "vel est donec", "subtitle": "sit amet nulla", "description": "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.", "price_detail": { "price": 861208, "discount": 59 }, "rating": { "rate": 38, "count": 168 }, "image": tireInflator, "create_date": 1251595611000, },
            { "id": "QwMAfA", "title": "lectus aliquam sit", "subtitle": "aliquam augue quam", "description": "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.", "price_detail": { "price": 863042, "discount": 99 }, "rating": { "rate": 70, "count": 266 }, "image": tireInflator, "create_date": 1713723403000, },
            { "id": "04XgKq", "title": "nunc", "subtitle": "volutpat", "description": "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.", "price_detail": { "price": 758525, "discount": 98 }, "rating": { "rate": 41, "count": 156 }, "image": tireInflator, "create_date": 1860260295000, },
            { "id": "x8FLb3", "title": "interdum mauris ullamcorper", "subtitle": "sapien varius ut", "description": "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.", "price_detail": { "price": 333896, "discount": 36 }, "rating": { "rate": 36, "count": 156 }, "image": tireInflator, "create_date": 1242553079000, },
            { "id": "dhpvoQ", "title": "et eros", "subtitle": "in quam fringilla", "description": "Sed ante. Vivamus tortor. Duis mattis egestas metus.", "price_detail": { "price": 142616, "discount": 6 }, "rating": { "rate": 15, "count": 134 }, "image": tireInflator, "create_date": 1776428354000, },
            { "id": "gHkI7Q", "title": "parturient montes nascetur", "subtitle": "erat volutpat in", "description": "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.", "price_detail": { "price": 694511, "discount": 70 }, "rating": { "rate": 93, "count": 221 }, "image": tireInflator, "create_date": 1708040137000, },
            { "id": "hk8Vrr", "title": "nonummy", "subtitle": "semper", "description": "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.", "price_detail": { "price": 15791, "discount": 52 }, "rating": { "rate": 12, "count": 72 }, "image": tireInflator, "create_date": 1477224531000, },
            { "id": "a91ZEU", "title": "risus semper", "subtitle": "vel accumsan tellus", "description": "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.", "price_detail": { "price": 425304, "discount": 48 }, "rating": { "rate": 33, "count": 124 }, "image": tireInflator, "create_date": 1641180623000, },
            { "id": "CjIVhJ", "title": "dignissim vestibulum vestibulum", "subtitle": "proin", "description": "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.", "price_detail": { "price": 274172, "discount": 20 }, "rating": { "rate": 61, "count": 85 }, "image": tireInflator, "create_date": 1370796334000, },
            { "id": "t8J3CH", "title": "eget tempus", "subtitle": "vitae", "description": "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.", "price_detail": { "price": 833306, "discount": 98 }, "rating": { "rate": 83, "count": 77 }, "image": tireInflator, "create_date": 1597141864000, },
            { "id": "IJZkWj", "title": "vestibulum sit", "subtitle": "faucibus orci", "description": "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.", "price_detail": { "price": 909323, "discount": 36 }, "rating": { "rate": 74, "count": 58 }, "image": tireInflator, "create_date": 1068931187000, },
            { "id": "58EZeZ", "title": "phasellus", "subtitle": "quisque porta", "description": "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.", "price_detail": { "price": 538472, "discount": 79 }, "rating": { "rate": 28, "count": 63 }, "image": tireInflator, "create_date": 1266925342000, },
         ],
      },
   },
   users: [
      { "id": "M2U1", "name": "Ehsan", "username": "ebahari", "email": "e@g.com", "password": "P@$$w0rd!" },
      { "id": "Scph", "name": "Yorgo", "username": "ysanper0", "email": "yfuke0@bloglines.com", "password": "hWsU4zf11" },
      { "id": "Ilmu", "name": "Ellerey", "username": "efoldes1", "email": "ethomsson1@earthlink.net", "password": "YYZN9BSnDv" },
      { "id": "jCe3", "name": "Katee", "username": "kfiller2", "email": "kdelepine2@is.gd", "password": "TVsv2F" },
      { "id": "LPBF", "name": "Garnet", "username": "grieger3", "email": "gambrois3@cnn.com", "password": "3nzmNv85le7C" },
      { "id": "i0ti", "name": "Jenda", "username": "jpyffe4", "email": "jeye4@ihg.com", "password": "mJ7XUlqZdXC" }
   ],
   orders: [
      { "user_id": "M2U1", "order": [{ "product_id": "jpZ9Pl", "count": 2 }, { "product_id": "5fAzF6", "count": 1 }, { "product_id": "1F9V9b", "count": 4 },], "create_date": 1149261033000, "delivered": false, },
      { "user_id": "Ilmu", "order": [{ "product_id": "TG9cEo", "count": 2 },], "create_date": 1149261033000, "delivered": false, },
   ],
};

const DBSlice = createSlice({
   name: "DB",
   initialState,
   reducers: {
      // getItems(state) { state; }
   }
});

export const { getItems } = DBSlice.actions;
export default DBSlice.reducer;